/**
 * LingoFriends — Lesson Assembler
 *
 * DETERMINISTIC lesson assembly from AI-generated chunk content.
 *
 * ARCHITECTURE RULE (see .clinerules):
 *   The AI generates CONTENT (phrases, translations, distractors, contexts).
 *   This module builds ACTIVITIES (ActivityConfig objects).
 *   These two concerns are NEVER mixed.
 *
 * TEACH-FIRST 5-STEP PROGRESSION (Bug fix 2.3.4 + 2.3.8):
 *   Every chunk is taught through exactly these 5 steps in order:
 *   1. INTRODUCE  — INFO card showing phrase + translation (0 SunDrops)
 *   2. RECOGNIZE  — MC "What does [phrase] mean?" in native language (1 SunDrop)
 *   3. PRACTICE   — Fill-blank to complete the phrase (2 SunDrops)
 *   4. RECALL     — Translate native → target language (3 SunDrops)
 *   5. APPLY      — MC "When would you say [phrase]?" situational (2 SunDrops)
 *
 * This replaces the Phase 1.3 activitySequencer approach which picked quiz types
 * randomly from a pool. The sequencer caused Bug 2.3.8 — the same type could
 * appear twice on the same chunk (e.g., MC → MC or TRUE_FALSE → MC), making
 * lessons feel repetitive. The fixed 5-step sequence guarantees:
 *   - Every chunk gets FIVE DISTINCT activity types
 *   - INTRODUCE always precedes any quiz (Bug 2.3.4 compliance)
 *   - RECOGNIZE and APPLY are both MC but ask different questions
 *   - Activity difficulty escalates within each chunk
 *
 * The activitySequencer.ts is preserved for potential use in review/SRS mode
 * (Phase 3), but is NOT imported or used here.
 *
 * This module has ZERO dependency on the AI client. It is pure TypeScript
 * and always produces valid, fully-populated ActivityConfig objects.
 *
 * @module lessonAssembler
 */

import { GameActivityType } from '../types/game';
import type { ActivityConfig, LessonStep, LessonPlan } from '../types/game';
import { toLanguageName } from '../utils/languageUtils';

// activitySequencer is intentionally NOT imported here.
// The sequencer was used in Phase 1.3 for random variety but produced
// repetitive activity types across chunks (Bug 2.3.8). The fixed
// 5-step teach-first sequence (assembleTeachFirstSteps) is pedagogically
// superior and guarantees distinct activity types per chunk.
// The sequencer is still available for future review/SRS mode — see Phase 3 plans.

// ============================================================================
// TYPES — THE ONLY INTERFACE BETWEEN AI OUTPUT AND LESSON ASSEMBLY
// ============================================================================

/**
 * A single lexical chunk generated by the AI.
 *
 * CRITICAL CONTRACT:
 * - All distractors MUST be in the NATIVE language (same as nativeTranslation).
 *   Example for "Guten Morgen" (native = English):
 *     distractors: ["Good evening", "Good night", "Goodbye"]  ✅
 *     distractors: ["Guten Abend", "Gute Nacht", "Tschüss"]   ❌ (target language!)
 *
 * - All usage contexts MUST be in the NATIVE language.
 *
 * If the AI doesn't follow these rules, the validator will catch it.
 */
export interface GeneratedChunkContent {
  /** Phrase in the target language: "Guten Morgen" */
  targetPhrase: string;

  /** Translation in the native language: "Good morning" */
  nativeTranslation: string;

  /** Example sentence using the phrase in the target language: "Guten Morgen! Wie geht's?" */
  exampleSentence: string;

  /** When/how to use this phrase, in the native language: "Use as a morning greeting" */
  usageNote: string;

  /** Child-friendly explanation in the native language: "A polite way to say hello in the morning" */
  explanation: string;

  /**
   * 3 wrong translations in the NATIVE language.
   * Must be plausible (same semantic category) but clearly wrong.
   * NEVER in the target language.
   */
  distractors: [string, string, string];

  /** The correct situation for using this phrase, in the native language */
  correctUsageContext: string;

  /**
   * 3 wrong usage situations in the NATIVE language.
   * Must be plausible but incorrect.
   */
  wrongUsageContexts: [string, string, string];

  /**
   * AI-generated coaching introduction for this chunk (Task 2.0.07).
   * Spoken by the NPC via TTS when the step begins.
   * Written in the user's native language with target language examples.
   * Provides context, motivation, and personalization.
   * Example: "Let's learn how to greet someone in the morning! In German, you'd say 'Guten Morgen'."
   */
  coachingText?: string;
}

/**
 * Complete AI output for a lesson — CONTENT ONLY, no activity structure.
 * This is assembled into a LessonPlan by assembleLessonPlan().
 */
export interface AILessonContent {
  /** Lesson display title, e.g. "Morning Greetings" */
  title: string;

  /** Target language ISO code, e.g. "de" */
  targetLanguageCode: string;

  /** Native language ISO code, e.g. "en" */
  nativeLanguageCode: string;

  /** The chunks to teach in this lesson (2–4 recommended) */
  chunks: GeneratedChunkContent[];

  /** Learner interests used for personalising tutor text */
  interests?: string[];
}

// ============================================================================
// PUBLIC API
// ============================================================================

/**
 * Assemble a complete LessonPlan from AI-generated chunk content.
 *
 * This function is DETERMINISTIC — same input always produces same output.
 * It NEVER calls the AI or makes any network requests.
 *
 * TEACH-FIRST SEQUENCE (Bug fixes 2.3.4 + 2.3.8):
 * Each chunk goes through exactly 5 steps in a fixed order. The old
 * activitySequencer approach randomly selected types from a pool, which
 * caused repeated types within a single chunk's quiz steps. The fixed
 * sequence guarantees INFO → MC(meaning) → FILL_BLANK → TRANSLATE →
 * MC(usage context) — five distinct types per chunk, escalating difficulty.
 *
 * introChunks is populated so LessonView can show a LessonIntroCard
 * before step 0, giving learners a mental map of what they'll learn.
 *
 * @param content - AI-generated chunk content (from generateChunksForTopic)
 * @param lessonId - Unique lesson ID supplied by the caller
 * @param options - Optional settings (difficulty unused now, kept for API compat)
 * @returns A fully populated LessonPlan ready for LessonView
 */
export function assembleLessonPlan(
  content: AILessonContent,
  lessonId: string,
  options?: { difficulty?: number; seed?: number }
): LessonPlan {
  const targetLangName = toLanguageName(content.targetLanguageCode);

  // Build all steps using the fixed 5-step teach-first sequence per chunk.
  // This call order is guaranteed: INFO → MC → FILL_BLANK → TRANSLATE → MC(usage)
  const steps: LessonStep[] = [];
  for (const chunk of content.chunks) {
    steps.push(...assembleTeachFirstSteps(chunk, targetLangName));
  }

  const totalSunDrops = steps.reduce((sum, step) => sum + step.activity.sunDrops, 0);

  // Count distinct activity types for logging (should always be 4 — INFO, MC, FB, TRANSLATE)
  const activityTypes = new Set(steps.map(s => s.activity.type));

  console.log(
    `[lessonAssembler] Assembled ${steps.length} steps for ${content.chunks.length} chunks ` +
    `(${totalSunDrops} SunDrops, ${activityTypes.size} distinct types: ${[...activityTypes].join(', ')})`
  );

  return {
    id: lessonId,
    title: content.title,
    icon: '📚',
    skillPathId: content.title,
    lessonIndex: 0,
    steps,
    totalSunDrops,
    // LessonIntroCard preview data (Task 2.3.4)
    // One entry per chunk — shown before step 0 so learners know what's coming.
    introChunks: content.chunks.map(c => ({
      targetPhrase: c.targetPhrase,
      nativeTranslation: c.nativeTranslation,
    })),
  };
}

/**
 * Get the correct option index for a shuffled multiple-choice question.
 *
 * Deterministic: same answer string → same position every time.
 * The correct answer won't always be at index 0 (which is obviously wrong)
 * but the position is stable across renders.
 *
 * @param correctAnswer - The correct option text
 * @returns Index 0-3
 */
export function getCorrectIndex(correctAnswer: string): number {
  // Use string length mod 4 — simple, deterministic, distributes across 0-3
  return correctAnswer.length % 4;
}

// ============================================================================
// CORE ASSEMBLY — TEACH-FIRST 5-STEP PROGRESSION
// ============================================================================

/**
 * Build the 5 teach-first steps for a single chunk.
 *
 * ORDER IS MANDATORY:
 *   1. INTRODUCE  (INFO)            — learner sees the phrase first
 *   2. RECOGNIZE  (MULTIPLE_CHOICE) — guided MC with hint available
 *   3. PRACTICE   (FILL_BLANK)      — complete part of the phrase
 *   4. RECALL     (TRANSLATE)       — full translation from native to target
 *   5. APPLY      (MULTIPLE_CHOICE) — contextual usage question
 */
function assembleTeachFirstSteps(
  chunk: GeneratedChunkContent,
  targetLangName: string
): LessonStep[] {
  return [
    buildIntroduceStep(chunk),
    buildRecognizeStep(chunk),
    buildPracticeStep(chunk),
    buildRecallStep(chunk, targetLangName),
    buildApplyStep(chunk),
  ];
}

// ── STEP 1: INTRODUCE ────────────────────────────────────────────────────────

/**
 * Show the phrase + translation. No quiz. No pressure.
 * The learner MUST see this before any quiz step.
 * 
 * coachingText is included for TTS playback (Task 2.0.07).
 */
function buildIntroduceStep(chunk: GeneratedChunkContent): LessonStep {
  return {
    tutorText: `📚 New phrase: "${chunk.targetPhrase}"`,
    helpText: chunk.explanation,
    coachingText: chunk.coachingText, // AI-generated intro for TTS
    activity: {
      type: GameActivityType.INFO,
      title: chunk.targetPhrase,
      content: `${chunk.targetPhrase} = "${chunk.nativeTranslation}"`,
      explanation: chunk.explanation,
      example: chunk.exampleSentence,
      sunDrops: 0,
    },
  };
}

// ── STEP 2: RECOGNIZE ────────────────────────────────────────────────────────

/**
 * Multiple choice: "What does [target phrase] mean?"
 * Options are all in the NATIVE language (correct answer + 3 distractors).
 * Hint reminds the learner of the answer — this is GUIDED practice.
 */
function buildRecognizeStep(chunk: GeneratedChunkContent): LessonStep {
  const options = shuffleWithCorrectAt(chunk.nativeTranslation, chunk.distractors);
  const correctIndex = getCorrectIndex(chunk.nativeTranslation);

  return {
    tutorText: `Let's check — what does "${chunk.targetPhrase}" mean?`,
    helpText: `Remember: "${chunk.targetPhrase}" = "${chunk.nativeTranslation}"`,
    activity: {
      type: GameActivityType.MULTIPLE_CHOICE,
      question: `What does "${chunk.targetPhrase}" mean?`,
      options,
      correctIndex,
      hint: `"${chunk.targetPhrase}" = "${chunk.nativeTranslation}"`,
      sunDrops: 1,
    },
  };
}

// ── STEP 3: PRACTICE ─────────────────────────────────────────────────────────

/**
 * Fill in the blank — recall part of the phrase.
 *
 * Multi-word phrase → blank the last word: "Guten ___"
 * Single-word phrase → "___ = 'translation'" format
 *
 * Hint is available but not shown by default.
 */
function buildPracticeStep(chunk: GeneratedChunkContent): LessonStep {
  const sentence = buildFillBlankSentence(chunk);
  const correctAnswer = getFillBlankAnswer(chunk);
  const acceptedAnswers = getFillBlankAcceptedAnswers(chunk);

  return {
    tutorText: `Practice time! Complete this phrase.`,
    helpText: `The full phrase is: "${chunk.targetPhrase}"`,
    activity: {
      type: GameActivityType.FILL_BLANK,
      sentence,
      correctAnswer,
      acceptedAnswers,
      hint: `"${chunk.targetPhrase}" = "${chunk.nativeTranslation}"`,
      sunDrops: 2,
    },
  };
}

// ── STEP 4: RECALL ────────────────────────────────────────────────────────────

/**
 * Translate from native language to target language.
 * No hints shown by default — this is where retention is tested.
 * Multiple accepted answer variants handle capitalisation and punctuation.
 */
function buildRecallStep(chunk: GeneratedChunkContent, targetLangName: string): LessonStep {
  const acceptedAnswers = getTranslateAcceptedAnswers(chunk);

  return {
    tutorText: `Your turn! How do you say "${chunk.nativeTranslation}" in ${targetLangName}?`,
    helpText: `Think about the phrase we just practised...`,
    activity: {
      type: GameActivityType.TRANSLATE,
      sourcePhrase: chunk.nativeTranslation,
      // correctAnswer is the canonical form — Translate.tsx requires this for its
      // validation check and "show answer after X wrong attempts" feature.
      // acceptedAnswers includes lowercase/punctuation variants so kids aren't penalised.
      correctAnswer: chunk.targetPhrase,
      acceptedAnswers,
      hint: `It starts with "${chunk.targetPhrase.substring(0, 3)}..."`,
      sunDrops: 3,
    },
  };
}

// ── STEP 5: APPLY ─────────────────────────────────────────────────────────────

/**
 * Contextual multiple choice: "When would you say [phrase]?"
 * Options are all in the NATIVE language (correct situation + 3 wrong situations).
 */
function buildApplyStep(chunk: GeneratedChunkContent): LessonStep {
  const options = shuffleWithCorrectAt(chunk.correctUsageContext, chunk.wrongUsageContexts);
  const correctIndex = getCorrectIndex(chunk.correctUsageContext);

  return {
    tutorText: `Great! Now, when would you say "${chunk.targetPhrase}"?`,
    helpText: chunk.usageNote,
    activity: {
      type: GameActivityType.MULTIPLE_CHOICE,
      question: `When would you say "${chunk.targetPhrase}"?`,
      options,
      correctIndex,
      hint: chunk.usageNote,
      sunDrops: 2,
    },
  };
}

// ============================================================================
// ADDITIONAL ACTIVITY BUILDERS FOR VARIETY
// ============================================================================

/**
 * Build a TRUE_FALSE activity for a chunk.
 *
 * The learner evaluates whether a statement about the phrase is true.
 * This is a recognition-tier activity (easiest).
 */
function buildTrueFalseStep(chunk: GeneratedChunkContent): LessonStep {
  // Randomly decide whether to show a true or false statement
  // Use deterministic "randomness" based on phrase length
  const showTrue = chunk.targetPhrase.length % 2 === 0;

  let statement: string;
  let isTrue: boolean;

  if (showTrue) {
    statement = `"${chunk.targetPhrase}" means "${chunk.nativeTranslation}"`;
    isTrue = true;
  } else {
    // Create a false statement using a wrong translation
    const wrongTranslation = chunk.distractors[0];
    statement = `"${chunk.targetPhrase}" means "${wrongTranslation}"`;
    isTrue = false;
  }

  return {
    tutorText: `Quick check: Is this statement true or false?`,
    helpText: `Think about what "${chunk.targetPhrase}" means...`,
    activity: {
      type: GameActivityType.TRUE_FALSE,
      statement,
      isTrue,
      hint: `"${chunk.targetPhrase}" = "${chunk.nativeTranslation}"`,
      sunDrops: 1,
    },
  };
}

/**
 * Build a MATCHING activity for a chunk.
 *
 * The learner matches the target phrase with its translation.
 * We include the correct chunk + 3 distractors for a 4-pair matching game.
 *
 * Note: This activity works best when we have multiple chunks available.
 * For a single chunk, we generate pseudo-distractors from the chunk's distractors.
 */
function buildMatchingStep(chunk: GeneratedChunkContent): LessonStep {
  // Build pairs: correct pair + 3 distractor pairs
  // For matching, we need target phrases paired with native translations
  const pairs = [
    { left: chunk.targetPhrase, right: chunk.nativeTranslation },
    // Create distractor pairs (wrong pairings)
    { left: chunk.distractors[0], right: chunk.distractors[1] },
    { left: chunk.distractors[1], right: chunk.distractors[2] },
    { left: chunk.distractors[2], right: chunk.distractors[0] },
  ];

  // Shuffle the pairs for variety
  const shuffledPairs = shufflePairs(pairs);

  return {
    tutorText: `Match the phrases with their meanings!`,
    helpText: `Find the pair: "${chunk.targetPhrase}" = "${chunk.nativeTranslation}"`,
    activity: {
      type: GameActivityType.MATCHING,
      pairs: shuffledPairs,
      hint: `"${chunk.targetPhrase}" means "${chunk.nativeTranslation}"`,
      sunDrops: 2,
    },
  };
}

/**
 * Build a WORD_ARRANGE activity for a chunk.
 *
 * The learner arranges scrambled words to form the target phrase.
 * This is a production-tier activity (harder).
 */
function buildWordArrangeStep(chunk: GeneratedChunkContent): LessonStep {
  // Split the phrase into words
  const words = chunk.targetPhrase.split(/\s+/);

  // Create a scrambled version (shuffled array)
  const scrambledWords = shuffleWords(words);

  return {
    tutorText: `Arrange the words to form: "${chunk.nativeTranslation}"`,
    helpText: `The correct phrase is: "${chunk.targetPhrase}"`,
    activity: {
      type: GameActivityType.WORD_ARRANGE,
      targetSentence: chunk.targetPhrase,
      scrambledWords,
      hint: `"${chunk.targetPhrase}" = "${chunk.nativeTranslation}"`,
      sunDrops: 3,
    },
  };
}

// ============================================================================
// ADDITIONAL HELPERS FOR VARIETY ACTIVITIES
// ============================================================================

/**
 * Shuffle an array of words using Fisher-Yates algorithm.
 * Uses deterministic randomness based on the words themselves.
 */
function shuffleWords(words: string[]): string[] {
  const result = [...words];
  // Simple shuffle - swap each element with a random position
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor((i + words[i].length) % (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}

/**
 * Shuffle pairs array for variety in matching activities.
 */
function shufflePairs(pairs: Array<{ left: string; right: string }>): Array<{ left: string; right: string }> {
  const result = [...pairs];
  for (let i = result.length - 1; i > 0; i--) {
    const j = (i * 3) % (i + 1);
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}

// ============================================================================
// HELPERS
// ============================================================================

/**
 * Shuffle options so the correct answer lands at a deterministic position.
 *
 * Position = correctAnswer.length % 4, so it varies by content
 * but is stable across renders. This prevents the correct answer from
 * always appearing at index 0 (too obvious) while remaining testable.
 *
 * @param correctAnswer - The correct option text
 * @param wrongAnswers - Exactly 3 wrong options
 * @returns Array of 4 options with correct answer at getCorrectIndex() position
 */
function shuffleWithCorrectAt(
  correctAnswer: string,
  wrongAnswers: [string, string, string]
): string[] {
  const position = getCorrectIndex(correctAnswer);
  // Start with the 3 wrong answers
  const options: string[] = [...wrongAnswers];
  // Insert correct answer at the calculated position
  options.splice(position, 0, correctAnswer);
  return options;
}

/**
 * Build the fill-in-the-blank sentence string.
 *
 * Multi-word: blank the last word → "Guten ___"
 * Single word: use format        → "___ = 'Good morning'"
 */
function buildFillBlankSentence(chunk: GeneratedChunkContent): string {
  const words = chunk.targetPhrase.split(/\s+/);
  if (words.length >= 2) {
    // Blank the last word: "Guten ___"
    return words.slice(0, -1).join(' ') + ' ___';
  }
  // Single word: "___ = 'translation'"
  return `___ = "${chunk.nativeTranslation}"`;
}

/**
 * Get the expected fill-in-the-blank answer.
 *
 * For multi-word phrases, this is the last word.
 * For single words, this is the whole word.
 */
function getFillBlankAnswer(chunk: GeneratedChunkContent): string {
  const words = chunk.targetPhrase.split(/\s+/);
  return words.length >= 2 ? words[words.length - 1] : chunk.targetPhrase;
}

/**
 * Get all accepted answers for fill-in-the-blank, including:
 * - Exact answer
 * - Lowercase variant
 * - Punctuation-stripped variants
 *
 * Deduplicated to avoid redundant entries.
 */
function getFillBlankAcceptedAnswers(chunk: GeneratedChunkContent): string[] {
  const answer = getFillBlankAnswer(chunk);
  const stripped = answer.replace(/[!?.,;:]/g, '').trim();
  return [...new Set([
    answer,
    answer.toLowerCase(),
    stripped,
    stripped.toLowerCase(),
  ])];
}

/**
 * Get all accepted answers for the translate step.
 *
 * Includes the exact phrase, lowercase variant, and punctuation-stripped
 * variants so kids don't get penalised for minor formatting differences.
 */
function getTranslateAcceptedAnswers(chunk: GeneratedChunkContent): string[] {
  const phrase = chunk.targetPhrase;
  const stripped = phrase.replace(/[!?.,;:]/g, '').trim();
  return [...new Set([
    phrase,
    phrase.toLowerCase(),
    stripped,
    stripped.toLowerCase(),
  ])];
}
